// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwORpSKF96TCnlmHEI6lxUEJSLEHNS-J4',
    appId: '1:70267147150:web:7e74f069f576c3cea18adf',
    messagingSenderId: '70267147150',
    projectId: 'doubt-solving-app-97c3d',
    authDomain: 'doubt-solving-app-97c3d.firebaseapp.com',
    storageBucket: 'doubt-solving-app-97c3d.firebasestorage.app',
    measurementId: 'G-8RD3CHHL95',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWZJA9Fs3os3d8ORZm1kbirw5Skg5D8Aw',
    appId: '1:70267147150:android:49792cf7377af130a18adf',
    messagingSenderId: '70267147150',
    projectId: 'doubt-solving-app-97c3d',
    storageBucket: 'doubt-solving-app-97c3d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSvI6a2FHkJARAcxbvYRFOlcdHtNzsobE',
    appId: '1:70267147150:ios:c318cd99393d9b77a18adf',
    messagingSenderId: '70267147150',
    projectId: 'doubt-solving-app-97c3d',
    storageBucket: 'doubt-solving-app-97c3d.firebasestorage.app',
    iosBundleId: 'com.example.newapp11',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSvI6a2FHkJARAcxbvYRFOlcdHtNzsobE',
    appId: '1:70267147150:ios:c318cd99393d9b77a18adf',
    messagingSenderId: '70267147150',
    projectId: 'doubt-solving-app-97c3d',
    storageBucket: 'doubt-solving-app-97c3d.firebasestorage.app',
    iosBundleId: 'com.example.newapp11',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwORpSKF96TCnlmHEI6lxUEJSLEHNS-J4',
    appId: '1:70267147150:web:24074bf1d95c61e9a18adf',
    messagingSenderId: '70267147150',
    projectId: 'doubt-solving-app-97c3d',
    authDomain: 'doubt-solving-app-97c3d.firebaseapp.com',
    storageBucket: 'doubt-solving-app-97c3d.firebasestorage.app',
    measurementId: 'G-C319BFHG4R',
  );
}
